[info]
#开始在一起的日期，格式参考 2023-10-01
start_date=2023-10-01
#你女朋友所在的城市，写城市名或省份名或者所在的区  如“西安”
city1=南海
#你女朋友的家乡，写城市名或省份名或者所在的区  如 "商洛"
city2=新会
#你女朋友的生日，注意格式只写*月*日 如："12-02"
birthday_lover=12-02
#你的生日,注意格式只写*月*日 如："06-27"
birthday_my=06-27
#以下为微信测试号的参数，在申请时会显示
app_id=wxe4ef67f6894ed609
app_secret=1b76f1812ca2b6ad7f874124c868e742
#消息模板ID，在微信测试号中添加模板会自动生成ID
template_id＝iVMln3QcuFutpL3qh_-5ETNBHz4rEWe3C7e15T-S8s8
#接收消息的用户ID，让你的女朋友扫微信测试号的二维码，获取微信用户ID
#如有多个女朋友或者女朋友有多个微信，请使用以下格式","隔开
#user_id=or0Fu2ymJTTVfUKEfIqFwrHuVtnE




